version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DATABASE: 'mlauthentication'
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: 'mlauth'
      # You can use whatever password you like
      POSTGRES_PASSWORD: '1234'
      # Password for root access
      POSTGRES_ROOT_PASSWORD: 'password'
    ports:
      - "3409:3306"

  php:
    build: ./docker/php
    container_name: php_ml
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:rw
    depends_on:
      - db

  http:
    image: nginx:1-alpine
    depends_on:
      - php
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html:ro
    ports:
      - "8888:80"

volumes:
  db-data: {}
